### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Zbless** [atomistic-machine-learning/cG-SchNet#2]
Hello, thank you very much for your previous work. In the process of running your code, https://ndownloader.figshare.com/files/3195404 403 error occurred in data link. How can I solve this problem?

**Comment by NiklasGebauer** [comment]
Hello,
you're welcome!
Maybe this was a temporary thing, the link is working for me right now. Please let me know if the error persists for you, then I'd see if we can find a more reliable source and replace the link. However, we currently link to the official data repository  of QM9 which should be the most appropriate source.
If you are connected via a VPN it can also help to turn the VPN off (if possible) since some hosts block requests if too many are coming from the same IP.

**Comment by Zbless** [comment]
hi，
Thank you very much for your timely reply, which is very useful to me.
